### ISSUE TITLE
Invalid signupgenius links for the Rubio Canyon Trail Work on events calendar & webpage

### ISSUE THREAD

**Issue by rhass** [trailangeles/trailangeles#121]
I was looking at the [events page](https://trailangeles.org/events/) today and found that the [signupgenius links](https://www.signupgenius.com/go/10c0f4aabae2ba4ffc61-volunteer2) for the Rubio Canyon Trail Work are invalid.

I also emailed SM.FS.ANFVolunteers@usda.gov in case they are in contact with the calendar maintainer and/or project manager for this trail project.

**Comment by maxogden** [comment]
@rhass Hey sorry I missed this issue before! We have some bugs on our events page still... I have some crappy code that pulls google calender descriptions but I've been having issues rendering rich text formatting on the site. For now the FB link on https://trailangeles.org/volunteer-groups/rubio-canyon-trail-crew/ is the recommended way to sign up for the Rubio canyon crew

**Comment by rhass** [comment]
@maxogden No worries! I think it may have been an issue with the link itself in the calendar (bad data). I just looked at the calendar now, and it looks like it has been updated with email information, which I don't recall being there previously.
